// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BenchLIB",
    products: [
        .library(name: "BenchLIB", targets: ["BenchLIB"]),
    ],
    targets: [
        .target(name: "BenchLIB", dependencies: []),        
    ]
)
