// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Benchmark",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(name: "Benchmark", targets: ["Benchmark"])
    ],
    dependencies: [
        .package(url: "https://github.com/onevcat/Kingfisher.git", "7.1.2"..<"8.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Kingfisher", package: "Kingfisher")
            ],
            path: "."
        )
    ]
)
